/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.rsystems.share.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import org.rsystems.share.service.persistence.AlbumPK;

import java.io.Serializable;

/**
 * The base model interface for the Album service. Represents a row in the &quot;Share_Album&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.rsystems.share.model.impl.AlbumModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.rsystems.share.model.impl.AlbumImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Album
 * @see org.rsystems.share.model.impl.AlbumImpl
 * @see org.rsystems.share.model.impl.AlbumModelImpl
 * @generated
 */
@ProviderType
public interface AlbumModel extends BaseModel<Album> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a album model instance should use the {@link Album} interface instead.
	 */

	/**
	 * Returns the primary key of this album.
	 *
	 * @return the primary key of this album
	 */
	public AlbumPK getPrimaryKey();

	/**
	 * Sets the primary key of this album.
	 *
	 * @param primaryKey the primary key of this album
	 */
	public void setPrimaryKey(AlbumPK primaryKey);

	/**
	 * Returns the album_id of this album.
	 *
	 * @return the album_id of this album
	 */
	public int getAlbum_id();

	/**
	 * Sets the album_id of this album.
	 *
	 * @param album_id the album_id of this album
	 */
	public void setAlbum_id(int album_id);

	/**
	 * Returns the shared_user of this album.
	 *
	 * @return the shared_user of this album
	 */
	@AutoEscape
	public String getShared_user();

	/**
	 * Sets the shared_user of this album.
	 *
	 * @param shared_user the shared_user of this album
	 */
	public void setShared_user(String shared_user);

	/**
	 * Returns the album_name of this album.
	 *
	 * @return the album_name of this album
	 */
	@AutoEscape
	public String getAlbum_name();

	/**
	 * Sets the album_name of this album.
	 *
	 * @param album_name the album_name of this album
	 */
	public void setAlbum_name(String album_name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Album album);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Album> toCacheModel();

	@Override
	public Album toEscapedModel();

	@Override
	public Album toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}