/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rsystems.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.rsystems.model.PhotoAppConfiguration;

import com.rsystems.service.PhotoAppConfigurationLocalServiceUtil;

/**
 * The extended model base implementation for the PhotoAppConfiguration service. Represents a row in the &quot;photoapplication_PhotoAppConfiguration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhotoAppConfigurationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhotoAppConfigurationImpl
 * @see PhotoAppConfiguration
 * @generated
 */
@ProviderType
public abstract class PhotoAppConfigurationBaseImpl
	extends PhotoAppConfigurationModelImpl implements PhotoAppConfiguration {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a photo app configuration model instance should use the {@link PhotoAppConfiguration} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PhotoAppConfigurationLocalServiceUtil.addPhotoAppConfiguration(this);
		}
		else {
			PhotoAppConfigurationLocalServiceUtil.updatePhotoAppConfiguration(this);
		}
	}
}