/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rsystems.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the PhotoAppConfiguration service. Represents a row in the &quot;photoapplication_PhotoAppConfiguration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rsystems.model.impl.PhotoAppConfigurationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rsystems.model.impl.PhotoAppConfigurationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhotoAppConfiguration
 * @see com.rsystems.model.impl.PhotoAppConfigurationImpl
 * @see com.rsystems.model.impl.PhotoAppConfigurationModelImpl
 * @generated
 */
@ProviderType
public interface PhotoAppConfigurationModel extends BaseModel<PhotoAppConfiguration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a photo app configuration model instance should use the {@link PhotoAppConfiguration} interface instead.
	 */

	/**
	 * Returns the primary key of this photo app configuration.
	 *
	 * @return the primary key of this photo app configuration
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this photo app configuration.
	 *
	 * @param primaryKey the primary key of this photo app configuration
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this photo app configuration.
	 *
	 * @return the uuid of this photo app configuration
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this photo app configuration.
	 *
	 * @param uuid the uuid of this photo app configuration
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the config name of this photo app configuration.
	 *
	 * @return the config name of this photo app configuration
	 */
	@AutoEscape
	public String getConfigName();

	/**
	 * Sets the config name of this photo app configuration.
	 *
	 * @param configName the config name of this photo app configuration
	 */
	public void setConfigName(String configName);

	/**
	 * Returns the value1 of this photo app configuration.
	 *
	 * @return the value1 of this photo app configuration
	 */
	@AutoEscape
	public String getValue1();

	/**
	 * Sets the value1 of this photo app configuration.
	 *
	 * @param value1 the value1 of this photo app configuration
	 */
	public void setValue1(String value1);

	/**
	 * Returns the value2 of this photo app configuration.
	 *
	 * @return the value2 of this photo app configuration
	 */
	@AutoEscape
	public String getValue2();

	/**
	 * Sets the value2 of this photo app configuration.
	 *
	 * @param value2 the value2 of this photo app configuration
	 */
	public void setValue2(String value2);

	/**
	 * Returns the value3 of this photo app configuration.
	 *
	 * @return the value3 of this photo app configuration
	 */
	@AutoEscape
	public String getValue3();

	/**
	 * Sets the value3 of this photo app configuration.
	 *
	 * @param value3 the value3 of this photo app configuration
	 */
	public void setValue3(String value3);

	/**
	 * Returns the value4 of this photo app configuration.
	 *
	 * @return the value4 of this photo app configuration
	 */
	@AutoEscape
	public String getValue4();

	/**
	 * Sets the value4 of this photo app configuration.
	 *
	 * @param value4 the value4 of this photo app configuration
	 */
	public void setValue4(String value4);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PhotoAppConfiguration photoAppConfiguration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PhotoAppConfiguration> toCacheModel();

	@Override
	public PhotoAppConfiguration toEscapedModel();

	@Override
	public PhotoAppConfiguration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}